services:
###########################################################
##   User Preferences Service + Dapr sidecar             ##
###########################################################
  thenewsreporter.accessors.userpreferencesservice:
    container_name: User-Preferences-Service
    image: ${DOCKER_REGISTRY-}thenewsreporteraccessorsuserpreferencesservice
    build:
      context: .
      dockerfile: Accessors/TheNewsReporter.Accessors.UserPreferencesService/Dockerfile
    ports:
        - "5000:8080"
        - "5001:8081"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:8080
        - MongoDatabase__ConnectionString=mongodb://mongodb-service:27017
    depends_on:
        - mongodb-service
    networks:
        - news-reporter-network
      
  thenewsreporter.accessors.userpreferencesservice-dapr:
    container_name: User-Preferences-Service-Dapr
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "8080",
        "-app-id", "user-preferences-service", 
        "-app-protocol", "http",
        "-dapr-http-port", "3500", 
        "--resources-path","./dapr/components",
        "-config", "dapr/config.yaml"]
    volumes:
        - "./dapr:/dapr" 
    depends_on:
        - thenewsreporter.accessors.userpreferencesservice
    network_mode: "service:thenewsreporter.accessors.userpreferencesservice"
    
###########################################################
##   News Aggregation Service                            ##
###########################################################
  thenewsreporter.accessors.newsaggregationservice:
    container_name: News-Aggregation-Service
    image: ${DOCKER_REGISTRY-}thenewsreporteraccessorsnewsaggregationservice
    build:
      context: .
      dockerfile: Accessors/TheNewsReporter.Accessors.NewsAggregationService/Dockerfile
    ports:
        - "5002:8080"
        - "5003:8081"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - NewsApiSettings__ApiKey=${NEWS_API_KEY}
    networks:
        - news-reporter-network
 
###########################################################
##   AI Assistent Service                                ##
###########################################################
  thenewsreporter.accessors.aiassistentservice:
    container_name: AI-Assistent-Service
    image: ${DOCKER_REGISTRY-}thenewsreporteraccessorsaiassistentservice
    build:
        context: .
        dockerfile: Accessors/TheNewsReporter.Accessors.AIAssistentService/Dockerfile
    ports:
        - "5004:8080"
        - "5005:8081"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - AIApiSettings__ApiKey=${AI_API_KEY} 
    networks:
        - news-reporter-network

###########################################################
##   News Api Manager +  Dapr sidecar                    ##
###########################################################
  thenewsreporter.managers.newsapimanager:
    container_name: News-Api-Manager
    image: ${DOCKER_REGISTRY-}thenewsreportermanagersnewsapimanager
    build:
      context: .
      dockerfile: Managers/TheNewsReporter.Managers.NewsApiManager/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        # - ASPNETCORE_URLS=http://+:8080
    ports:
        - "5006:8080"
        - "5007:8081"
    depends_on:
        - rabbitmq
        - thenewsreporter.accessors.userpreferencesservice
    networks:
        - news-reporter-network

  thenewsreporter.managers.newsapimanager-dapr:
    container_name: News-Api-Manager-Dapr
    image: "daprio/daprd:edge"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 120s
    command: ["./daprd",
        "-app-port", "8080",
        "-app-id", "news-api-manager", 
        "-app-protocol", "http",
        "-dapr-http-port", "3500", 
        "--resources-path","./dapr/components",
        "-config", "dapr/config.yaml"]
    volumes:
        - "./dapr:/dapr" 
    depends_on:
        - thenewsreporter.managers.newsapimanager
    network_mode: "service:thenewsreporter.managers.newsapimanager"




  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - news-reporter-network
 

  mongodb-service:
    container_name: MongoDB-Service
    image: mongo:latest
    ports:
        - 27027:27017
    networks:
        - news-reporter-network
    volumes:
        - mongo-data:/data/db
        - ./mongo-init:/docker-entrypoint-initdb.d





networks:
  news-reporter-network:
    driver: bridge
volumes:
  mongo-data:  


