services:
###########################################################
##   TheNewsReporter.Services.UserPreferencesService     ##
###########################################################
  thenewsreporter.accessors.userpreferencesservice:
    image: ${DOCKER_REGISTRY-}thenewsreporteraccessorsuserpreferencesservice
    build:
      context: .
      dockerfile: Accessors/TheNewsReporter.Accessors.UserPreferencesService/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - MongoDatabase__ConnectionString=mongodb://mongodb-service:27017
    depends_on:
      - mongodb-service
    networks:
        - news-reporter-network
      

  mongodb-service:
    image: mongo:latest
    ports:
        - 27027:27017
    networks:
        - news-reporter-network
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d


networks:
  news-reporter-network:
volumes:
  mongo-data:  