apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: setuserpreferencesqueue 
spec:
  type: bindings.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://rabbitmq:5672"
  - name: queueName
    value: setuserpreferencesqueue
  - name: vhost
    value: /
  - name: durable
    value: true
  - name: deleteWhenUnused
    value: false
  - name: ttlInSeconds
    value: 5
  - name: prefetchCount
    value: 3
  - name: exclusive
    value: false
  - name: maxPriority
    value: 5