apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notification-event
spec:
  topic: nots
  routes:
    default: /sendnotification
  pubsubname: notification-pub-sub
scopes:
  - notification-service
  - news-api-manager 
